<?php

namespace App\Mail;

use Illuminate\Bus\Queueable;
use Illuminate\Mail\Mailable;
use Illuminate\Mail\Mailables\Content;
use Illuminate\Mail\Mailables\Envelope;
use Illuminate\Queue\SerializesModels;

/**
 * The one-time code mail, for both registration verification and password
 * reset.
 *
 * Shared on purpose: the two flows differ in wording and nothing else, and a
 * second template would drift from the first within a release or two. The
 * wording is selected per-instance because the old template hardcoded
 * "Password Reset", which meant a cashier confirming their email at sign-up
 * was told they had requested a password reset they had never asked for --
 * alarming, and a support call every time.
 */
class OtpMail extends Mailable
{
    use Queueable, SerializesModels;

    /** Codes proving a new address during registration. */
    public const PURPOSE_VERIFICATION = 'verification';

    /** Codes authorising a password change. */
    public const PURPOSE_RESET = 'password_reset';

    private string $otp = '';

    public function __construct(
        private readonly string $purpose = self::PURPOSE_RESET,
    ) {}

    /**
     * Attach the code at send time.
     *
     * Separate from the constructor because the code is generated by
     * OtpService, which persists it before mailing. If it were a constructor
     * argument the value would exist in two places at once, and the row in the
     * database is the one an attacker's guess is actually checked against.
     */
    public function withCode(string $otp): static
    {
        $this->otp = $otp;

        return $this;
    }

    public function envelope(): Envelope
    {
        return new Envelope(
            subject: $this->isVerification()
                ? 'Verify your email address'
                : 'Your password reset code',
        );
    }

    public function content(): Content
    {
        return new Content(
            htmlString: $this->buildHtml(),
        );
    }

    private function isVerification(): bool
    {
        return $this->purpose === self::PURPOSE_VERIFICATION;
    }

    /**
     * Interpolated from config rather than hardcoded as "10 minutes" was,
     * so the mail cannot claim a window the verifier does not honour.
     */
    private function ttlMinutes(): int
    {
        return (int) config('security.otp.ttl_minutes', 10);
    }

    private function buildHtml(): string
    {
        [$heading, $intro, $footer] = $this->isVerification()
            ? [
                'Verify your email',
                'Use the code below to confirm your email address and finish setting up your account:',
                'If you did not create this account, you can safely ignore this email.',
            ]
            : [
                'Password Reset',
                'You requested a password reset. Use the code below to verify your identity:',
                'If you did not request a password reset, please ignore this email.',
            ];

        $ttl = $this->ttlMinutes();

        return <<<HTML
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
        </head>
        <body style="margin:0;padding:0;background-color:#f4f4f7;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;">
            <table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f4f4f7;padding:40px 0;">
                <tr>
                    <td align="center">
                        <table width="560" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:8px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.06);">
                            <tr>
                                <td style="background:linear-gradient(135deg,#7B2CBF,#9D4EDD);padding:32px 40px;text-align:center;">
                                    <h1 style="color:#ffffff;margin:0;font-size:24px;font-weight:600;">{$heading}</h1>
                                </td>
                            </tr>
                            <tr>
                                <td style="padding:40px;">
                                    <p style="color:#374151;font-size:16px;margin:0 0 16px;">{$intro}</p>
                                    <div style="background-color:#f9fafb;border:2px dashed #7B2CBF;border-radius:8px;padding:24px;text-align:center;margin:24px 0;">
                                        <span style="font-size:36px;font-weight:bold;color:#7B2CBF;letter-spacing:8px;">{$this->otp}</span>
                                    </div>
                                    <p style="color:#6b7280;font-size:14px;margin:0 0 8px;">This code will expire in <strong>{$ttl} minutes</strong>.</p>
                                    <p style="color:#6b7280;font-size:14px;margin:0;">{$footer}</p>
                                </td>
                            </tr>
                            <tr>
                                <td style="background-color:#f9fafb;padding:24px 40px;border-top:1px solid #e5e7eb;">
                                    <p style="color:#9ca3af;font-size:12px;margin:0;text-align:center;">This is an automated message. Please do not reply.</p>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        </body>
        </html>
        HTML;
    }
}
